### PR TITLE
Made the /environment/new route page much more responsive .

### PR DESCRIPTION
**Pull request by Kashyap1ankit**
In this pull request , 

1. I have created a new file called PageComp.tsx which returns the previous Page.tsx data 
2. Created a MobNav.tsx file that returns a new navigation bar that helps to show the contents of PageComp.tsx
3. Changed the padding , margin and width of few components to make it responsive
Screenshot 2024-06-29 132346
Screenshot 2024-06-29 134834
Screenshot 2024-06-29 134859

### CODE REVIEW

**Comment by ucarion** [comment]
Is the intention that this would be mergeable as-is?

**Comment by Kashyap1ankit** [comment]
Hi @ucarion 

Thank you for reviewing my PR. Yes, it is my intention that this PR is mergeable as-is. I have tested the changes thoroughly, and the page now responds correctly across different devices and screen sizes. 

Please let me know if you need any additional information or if there are any specific concerns you would like me to address.

Best regards,  
Ankit Kashyap

**Comment by ucarion** [comment]
I'm not sure a menu coming from the right is how I'd go about this. I think that's my first concern. Instead, I would expect a top menu on small screens, and and then a dropdown menu to open the contents of the sidebar?

That's a pretty big ask on my part, and I think the resulting PR is pretty substantial and going to need to get a lot of details right. I think this might be a bit of a big lift for a first contribution. I'm not going to deter you from contributing, but I want to make sure you know what you're getting into.

**Comment by Kashyap1ankit** [comment]
Hi @ucarion ,

Thank you for the feedback and for outlining your concerns. I understand your preference for a top menu on small screens with a dropdown to access the sidebar contents.

Given this direction, I am happy to revise my PR to align with these expectations. I recognize that it might be a substantial change, but I am eager to learn and contribute effectively.

Would you be able to provide any specific guidelines or examples that could help me ensure I get the details right? Additionally, any pointers on aspects to focus on or common pitfalls to avoid would be greatly appreciated.

Thank you again for your guidance. I look forward to your suggestions and am ready to make the necessary adjustments.

**Comment by ucarion** [comment]
Without diving in and trying this myself, my intuition is to try to borrow from https://ui.shadcn.com/ and https://tailwindui.com/components/application-ui/application-shells/sidebar to try to put something together. I know that's pretty vague advice, which is sort of why I'm trying to warn you this is probably going to be a difficult, prolonged PR.

**Pull request closed without merging**
